package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* lundi 3 novembre 2025 15 h 50 WAT
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
} // interface CalculatorOperations
